# Generated by Django 3.2.5 on 2021-07-07 03:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('publishedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.CharField(max_length=3, null=True)),
                ('fetched', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topicId', models.TextField(unique=True)),
                ('wiki', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.channel')),
                ('viewCount', models.BigIntegerField(default=0)),
                ('subscriberCount', models.IntegerField(default=0)),
                ('hiddenSubscriberCount', models.BooleanField(default=False)),
                ('videoCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='topics',
            field=models.ManyToManyField(to='db.TopicCategory'),
        ),
    ]
